apiVersion: apps/v1
kind: Deployment

metadata:
  name: iris-api-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: iris-api

  template:
    metadata:
      labels:
        app: iris-api

    spec:
      containers:
      - name: iris-api-container
        image: shivaaye04/iris-api:latest

        ports:
        - containerPort: 8000